services:

  app_blue:
    build:
      context: .
      dockerfile: blue/Dockerfile
    container_name: app_blue
    ports:
      - "3010:3000"
    env_file: .env
    networks:
      - appnet
  
  app_green:
    build:
      context: .
      dockerfile: green/Dockerfile
    container_name: app_green
    ports:
      - "4002:3000"
    env_file: .env
    networks:
      - appnet

  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - app_blue
    networks:
      - appnet

networks:
  appnet:
