version: '3.8'
services:
  tg_pro_app:
    build: .
    container_name: landingpage
    restart: always
    ports:
      - "3010:3000"
    command: >
      sh -c "npm run start"
    volumes:
      - .:/app
      - /app/node_modules